// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

function requireEnv(name: string, value: string | undefined): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new Error(
      [
        `Missing required environment variable: ${name}`,
        "",
        "For local development, create a `.env.local` file with the required Vite env vars:",
        "  VITE_SUPABASE_URL=...",
        "  VITE_SUPABASE_PUBLISHABLE_KEY=...",
      ].join("\n")
    );
  }
  return value;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Fail fast with a clear error if env vars are missing.
const REQUIRED_SUPABASE_URL = requireEnv("VITE_SUPABASE_URL", SUPABASE_URL);
const REQUIRED_SUPABASE_PUBLISHABLE_KEY = requireEnv("VITE_SUPABASE_PUBLISHABLE_KEY", SUPABASE_PUBLISHABLE_KEY);

export const supabase = createClient<Database>(REQUIRED_SUPABASE_URL, REQUIRED_SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});